name: Render slides

on:
  push:
    branches: [ master, main ]
    paths: 
      - "_slide/**"

permissions:
  contents: write

jobs:
  render-slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Slides
        uses: docker://marpteam/marp-cli:v4.0.3
        with:
          args: -I _slide/ -O assets/slide/
        env:
          MARP_USER: root:root